name: Prophet Forecasting Demo

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  forecast-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install prophet plotly pandas numpy matplotlib
        
    - name: Run Prophet forecasting
      run: python prophet_demo.py
        
    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Bot"
        
        # Check if there are any changes
        if [ -n "$(git status --porcelain)" ]; then
          git add -f outputs/
          git commit -m "Auto-update Prophet forecast results"
          git push
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sync-to-huggingface:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: forecast-analysis
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Check if app.py was modified
      id: check_files
      run: |
        if git diff --name-only HEAD~1 HEAD | grep -q "app.py"; then
          echo "app_modified=true" >> $GITHUB_OUTPUT
        else
          echo "app_modified=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Sync to HuggingFace
      if: steps.check_files.outputs.app_modified == 'true'
      run: |
        git clone https://huggingface.co/spaces/Talebi-user-2025678/prophet-demo hf-repo
        cp app.py hf-repo/
        cd hf-repo
        git config user.email "action@github.com"
        git config user.name "GitHub Action Bot"
        git add app.py
        if ! git diff --cached --quiet; then
          git commit -m "Auto-sync app.py from GitHub"
          git push
        fi
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
