name: Prophet Forecasting Demo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  forecast-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install prophet plotly pandas numpy matplotlib
        
    - name: Create outputs directory
      run: mkdir -p outputs
      
    - name: Run Prophet forecasting
      run: python prophet_demo.py
        
    - name: List generated files
      run: |
        echo "Generated files:"
        ls -la outputs/
        
    - name: Commit results to repository
      if: github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Bot"
        
        # Force add outputs (ignore .gitignore for this)
        git add -f outputs/
        
        if ! git diff --cached --quiet; then
          git commit -m "Auto-update Prophet forecast results"
          git push
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
